name: CI/CD Pipeline with Codacy and ZAP

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    name: Build Application
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install Dependencies
        run: npm install

  test:
    name: Run Unit Tests and Generate Coverage
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install Dependencies
        run: npm install
      - name: Run Tests
        run: npm test -- --coverage
      - name: Upload Coverage Report
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: coverage/

  static-analysis:
    name: Static Analysis with Codacy
    needs: [build, test]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Run Codacy Analysis
        uses: codacy/codacy-analysis-cli-action@v4
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          directory: .
      - name: Upload Codacy Report Logs
        uses: actions/upload-artifact@v3
        with:
          name: codacy-logs
          path: . 

  dynamic-analysis:
    name: Dynamic Analysis with OWASP ZAP
    needs: [build, test]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Start Application
        run: |
          npm install
          npm start &
          sleep 10
      - name: OWASP ZAP Scan
        uses: zaproxy/action-full-scan@v0.12.0
        with:
          target: 'http://localhost:3000'
          report: true
          format: 'html'
      - name: Save ZAP Reports
        run: |
          mkdir -p zap-reports
          cp /zap/wrk/* zap-reports/
      - name: Upload ZAP Reports
        uses: actions/upload-artifact@v3
        with:
          name: zap-reports
          path: zap-reports/
