name: CI/CD Pipeline with Build, Test, Static Analysis (Codacy), and Dynamic Analysis (OWASP ZAP)

on:
  push:
    branches:
      - main
  pull_request: 
    branches:
      - main

jobs:
  build:
    name: Build Application
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install Dependencies
        run: npm ci

  test:
    name: Run Unit Tests and Generate Coverage
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install Dependencies
        run: npm ci
      - name: Fix Jest Permissions
        run: chmod +x node_modules/.bin/jest
      - name: Run Tests
        run: npx jest --coverage
      - name: Upload Coverage Report
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: coverage/
      - name: Upload Jest Test Logs
        uses: actions/upload-artifact@v3
        with:
          name: jest-logs
          path: jest-logs/

  static-analysis:
    name: Static Analysis with Codacy
    needs: [build, test]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Run Codacy Analysis
        uses: codacy/codacy-analysis-cli-action@v4
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          directory: .
      - name: Upload Codacy Report Logs
        uses: actions/upload-artifact@v3
        with:
          name: codacy-logs
          path: codacy-logs/

  dynamic-analysis:
    name: Dynamic Analysis with OWASP ZAP
    needs: [build, test]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install Dependencies
        run: npm ci
      - name: Start Application
        run: |
          npm start & 
          sleep 10
      - name: OWASP ZAP Scan
        uses: zaproxy/action-full-scan@v0.12.0
        with:
          target: 'http://localhost:3000'
          cmd_options: '-r'
      - name: Save ZAP Reports
        run: |
          mkdir -p zap-reports
          cp /zap/wrk/* zap-reports/
      - name: Upload ZAP Reports
        uses: actions/upload-artifact@v3
        with:
          name: zap-reports
          path: zap-reports/
      - name: Upload ZAP Logs
        uses: actions/upload-artifact@v3
        with:
          name: zap-logs
          path: zap-logs/
